server:
  port: 8087

spring:
  datasource:
    username: postgres
    password: Teste3345#
    url: jdbc:postgresql://localhost:5432/ead-authuser
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

